id: 145eb07d-b055-43d1-9b22-57cc3b080eec
type: application
interactions:
- targetId: 545f56a6-4a4c-41d4-aa57-74a4157755e5
  type: service
  level: component
- targetId: 300d1609-2817-433b-869a-11a93aeb830d
  type: domain
  level: component
annotations:
- namespace: c4modeler
  name: position
  value:
    cc9059b5-2c47-45c8-87e9-22742ff02cd6:
      x: 140
      y: 124.5
name: NewApplication
description: Description for NewApplication
baseApiUrl: ca/baseapi
