id: cc9059b5-2c47-45c8-87e9-22742ff02cd6
type: web-application
interactions:
- targetId: 1a606085-f223-4991-99f8-b72872ac06b8
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    693f4e90-ed19-4b84-a08a-8af6cd09573a:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: 145eb07d-b055-43d1-9b22-57cc3b080eec
  type: application
- id: 300d1609-2817-433b-869a-11a93aeb830d
  type: domain
- id: 87069c1a-ab38-42fc-8274-b26f7705bfc4
  type: scenario
